### ISSUE TITLE
cannot set up any reminders

### ISSUE THREAD

**Issue by andrewjs18** [Sama34/AriesBelgium--Remember-Us-#1]
Omar,

I'm seeing the reminders link under users & groups now, but I'm still unable to set up any reminders.  I also checked the admin permissions to see if there were any permissions I needed to allow.

![128 apr 27](https://cloud.githubusercontent.com/assets/2748980/7341945/a1b77b98-ec79-11e4-9f89-5e3c2c46c2c2.jpg)

![127 apr 27](https://cloud.githubusercontent.com/assets/2748980/7341946/a90602ac-ec79-11e4-8aab-9c9cf2a74bf7.jpg)

**Comment by Sama34** [comment]
What is in the source code? If the it is caused by an PHP warning it may only be visible from at the end of the source code. I'm currently unable to run my local environment to test myself.

**Comment by andrewjs18** [comment]
here's the source when I click on the 'add reminder' tab within admin cp> users & groups > reminders:

_I don't know how to properly paste code in github so here's a link to it_

http://pastebin.com/PEXBSBRk

**Comment by andrewjs18** [comment]
apache errors when hitting the url: http://pastebin.com/eRPCBRGU

**Comment by Supryk** [comment]
change line 265 in plugin file to this 

global $mybb, $page, $db, $lang, $admin_options, $form;

**Comment by andrewjs18** [comment]
didn't change much on the error side:

http://pastebin.com/WxaBvtCz

**Comment by Supryk** [comment]
hmmm

global $mybb, $page, $db, $lang, $admin_options, $form, $form_container;

**Comment by Sama34** [comment]
The error seems to be related to my OUGC Feedback plugin, it is probably loading in there but it shouldn't.

**Comment by andrewjs18** [comment]
yeah, when I tail my error log and then click around inside the reminders tabs, those are the errors that show up (I'm the only one clicking around in the admin cp during this time).

**Comment by Sama34** [comment]
I fixed the issue in OUGC Feedback just FYI.

**Comment by andrewjs18** [comment]
just replace the plugins file without deactivating?

**Comment by andrewjs18** [comment]
seemed to fix the issue.  thanks, Omar.

**Comment by Sama34** [comment]
Yes just replace the file, the issue was just one line.
