### ISSUE TITLE
file does not exist error

### ISSUE THREAD

**Issue by andrewjs18** [Sama34/AriesBelgium--Remember-Us-#2]
when you hit 'add reminder' in users & groups>reminders, it throws an error for a file that does not exist.  I assume this is probably old code from Aries that needs to be removed:

[Sat May 02 01:28:47 2015] [error] [client IP] File does not exist: /jscripts/scriptaculous.js, referer: http://site.com/admin/index.php?module=user-rememberus&action=add

**Comment by Sama34** [comment]
I assume the error only appears in the logs but doesn't stop functionality, right?

I don't get such error just from acceding the add page.

Anyways, the fix removed the call to such file since Prototype is what MyBB 1.6 uses but MyBB 1.8 replaced it with jQuery.

I don't know where the effects where used if at all so please report weird behavior.

**Comment by Sama34** [comment]
Ok now I know what was its purpose was. Lets see if I can update the Prototype code to jQuery. I suck at JavaScript.

**Comment by andrewjs18** [comment]
I haven't set up any reminders to know if the plugin itself is working yet, but so far everything - at least in the admin cp - seems to work.  I'll set up some reminders either here shortly or in the morning.

I recalled seeing that 'file does not exist error' when I opened the other ticket and figured I'd check it again and log a new ticket if the error was still showing up in my logs.

**Comment by andrewjs18** [comment]
Shall I apply your code fixes above or wait?

**Comment by Sama34** [comment]
The file was to handle the _Conditions_ table in reminders. Without it it was not possible to add new conditions. I updated it but my JavaScript skill suck.

Hopefully somebody will come and do something about it.

I fixed it in d2ada264e88b495b211400e8ca35ac0cc762b7a2 but got the title wrong..

Just replace the files.
