### ISSUE TITLE
personalization options don't work in add reminder

### ISSUE THREAD

**Issue by andrewjs18** [Sama34/AriesBelgium--Remember-Us-#3]
I assume this is probably from the prototype javascript that was used in 1.6.  when you click on the options found in users & groups>reminders>add reminders, nothing works - i.e.: [Username], [User e-mail], etc.

![131 may 02](https://cloud.githubusercontent.com/assets/2748980/7440205/10350e84-f074-11e4-8072-c86a81a62eda.jpg)

**Comment by Sama34** [comment]
Hm, yeah that was fixed in 76b2118efe2495797eaad0f43bf4aa746549e698, ignore the status above which is not true. I god `3` in there instead of `2` >_>

**Comment by andrewjs18** [comment]
confirming that the fixes allow you to click on the options now.
